import {
  Home,
  LayoutDashboard,
  DollarSign,
  Boxes,
  Users,
  ShoppingCart,
  ClipboardList,
  Receipt,
  Truck,
  FolderKanban,
  Plus,
} from "lucide-react";
import { AgentConfig } from "@/components/agent-dashboard/types";

export const tenderTrackingConfig: AgentConfig = {
  agentId: "tender-tracking",
  agentName: "TENDER TRACKING AGENT",
  badgeText: "REAL-TIME TENDER AI",
  title: "TENDER TRACKING",
  variant: "compact-centered",
  accentColor: "cyan",
  sidebarItems: [
    { id: "home", label: "Home", icon: Home, href: "/#services" },
    { id: "dashboard", label: "Dashboard", icon: LayoutDashboard, isTab: true },
    { id: "financials", label: "Financials", icon: DollarSign, isTab: true },
    { id: "materials", label: "Materials", icon: Boxes, isTab: true },
    { id: "hr", label: "Human Resource", icon: Users, isTab: true },
    { id: "procurement", label: "Procurement", icon: ShoppingCart, isTab: true },
    { id: "work-tracking", label: "Work Tracking", icon: ClipboardList, isTab: true },
    { id: "billing", label: "Billing", icon: Receipt, isTab: true },
    { id: "vehicles", label: "Vehicles", icon: Truck, isTab: true },
  ],
  actionOptions: [
    {
      id: "project-1",
      optionNumber: "PROJECT 01",
      title: "Project 1",
      description: "Infrastructure & Commercial Bidding",
      icon: FolderKanban,
      badgeColor: "text-cyan-600 dark:text-cyan-400",
      iconBg: "bg-cyan-50 text-cyan-600 border-cyan-100 dark:bg-cyan-950/60 dark:text-cyan-400 dark:border-cyan-800",
      topBorderColor: "border-t-cyan-500",
    },
    {
      id: "project-2",
      optionNumber: "PROJECT 02",
      title: "Project 2",
      description: "Highway & Civil Works Tender",
      icon: FolderKanban,
      badgeColor: "text-indigo-600 dark:text-indigo-400",
      iconBg: "bg-indigo-50 text-indigo-600 border-indigo-100 dark:bg-indigo-950/60 dark:text-indigo-400 dark:border-indigo-800",
      topBorderColor: "border-t-indigo-500",
    },
    {
      id: "project-3",
      optionNumber: "PROJECT 03",
      title: "Project 3",
      description: "Industrial Plant Tender Bidding",
      icon: FolderKanban,
      badgeColor: "text-purple-600 dark:text-purple-400",
      iconBg: "bg-purple-50 text-purple-600 border-purple-100 dark:bg-purple-950/60 dark:text-purple-400 dark:border-purple-800",
      topBorderColor: "border-t-purple-500",
    },
    {
      id: "add-project",
      optionNumber: "NEW",
      title: "Add Project",
      description: "Create Project Placeholder",
      icon: Plus,
      badgeColor: "text-emerald-600 dark:text-emerald-400",
      iconBg: "bg-emerald-50 text-emerald-600 border-emerald-100 dark:bg-emerald-950/60 dark:text-emerald-400 dark:border-emerald-800",
      topBorderColor: "border-t-emerald-500",
    },
  ],
  searchTitle: "Quick Tender & Project Search",
  searchSubtitle: "Search tenders, projects, contractors, materials, or work...",
  searchPlaceholder: "Search tenders, projects, contractors, materials, or work...",
};
