import {
  Home,
  LayoutDashboard,
  FileText,
  Activity,
  Building2,
  ShoppingCart,
  Boxes,
  Store,
  Settings,
  Package,
  ClipboardList,
  PlusCircle,
} from "lucide-react";
import { AgentConfig } from "@/components/agent-dashboard/types";

export const procurementConfig: AgentConfig = {
  agentId: "procurement",
  agentName: "PROCUREMENT AGENT",
  badgeText: "PROCUREMENT WORKSPACE",
  title: "MANAGE PROCUREMENT",
  variant: "compact-centered",
  accentColor: "purple",
  sidebarItems: [
    { id: "home", label: "Home", icon: Home, href: "/" },
    { id: "employer-dashboard", label: "Employer Dashboard", icon: LayoutDashboard, href: "/employer/dashboard" },
    { id: "dashboard", label: "Dashboard", icon: LayoutDashboard, isTab: true },
    { id: "details", label: "Procurement Details", icon: FileText, isTab: true },
    { id: "status", label: "Current Status", icon: Activity, isTab: true },
    { id: "companies-out", label: "Procurement to Companies", icon: Building2, isTab: true },
    { id: "get-procurement", label: "Get Procurement", icon: ShoppingCart, isTab: true },
    { id: "material-details", label: "Material Requirement Detail", icon: Boxes, isTab: true },
    { id: "companies", label: "Procurement Companies", icon: Store, isTab: true },
    { id: "settings", label: "Settings", icon: Settings, isTab: true },
    { id: "new-request", label: "New Request", icon: PlusCircle, isTab: true },
    { id: "saved-requests", label: "Saved Requests", icon: ClipboardList, isTab: true },
  ],
  actionOptions: [
    {
      id: "provide",
      optionNumber: "OPTION 01",
      title: "Provide Procurement",
      description: "Supplier and catalog tools are planned and are not available yet.",
      icon: Package,
      badgeColor: "text-purple-600 dark:text-purple-400",
      iconBg: "bg-purple-50 text-purple-600 border-purple-100 dark:bg-purple-950/60 dark:text-purple-400 dark:border-purple-800",
      topBorderColor: "border-t-purple-500",
    },
    {
      id: "get",
      optionNumber: "OPTION 02",
      title: "Get Procurement",
      description: "Create and manage material requests for your projects.",
      icon: ShoppingCart,
      badgeColor: "text-indigo-600 dark:text-indigo-400",
      iconBg: "bg-indigo-50 text-indigo-600 border-indigo-100 dark:bg-indigo-950/60 dark:text-indigo-400 dark:border-indigo-800",
      topBorderColor: "border-t-indigo-500",
    },
  ],
  searchTitle: "",
  searchSubtitle: "",
  searchPlaceholder: "Search saved material requests...",
};
